### ISSUE TITLE
Asociados. Añadir checkbox de certificado negativo de delitos sexuales, y poder filtrar sobre ello.

### ISSUE THREAD

**Issue by llunaCreixent** [fev/cudu#22]

**Comment by ScoutsFEV** [comment]
Esto también es de las cosas más importantes, y demandadas por los equipos asociativos para la gestión por parte de los técnicos.

**Comment by llunaCreixent** [comment]
Filtra en la pantalla de técnico y en la pantalla de asociado.
Una nueva issue: Necesidad de validación del campo por el técnico.
