### ISSUE TITLE
AC01 i AC02: Revisar funcionament de carrec i dades formatives

### ISSUE THREAD

**Issue by AmaiaMCastanos** [fev/cudu#59]
Els apartat de “Voluntariat” i “Formació” de les persones voluntàries NO funciona. NO es queda a la BBDD.

- [x] Test de funcionalidad:

             - [ ] Apartado voluntariado
             - [ ] Apartado formación

- [x] Revision BBDD
- [x] Revisión  del camino MVC

**Comment by AmaiaMCastanos** [comment]
APARTADO VOLUNTARIADO:

- Los datos se guardan pero la visualización de estos solamente funciona tras salir y volver a entrar a la ficha de la persona.

APARTADO FORMACIÓN:
- No se guarda en la base de datos.

**Comment by llunaCreixent** [comment]
APARTADO VOLUNTARIADO:

- Habría que ver qué pasa en el frontend cuando se clicka en "guardar". Envía los datos al backend pero los borra.

**Comment by AmaiaMCastanos** [comment]
El apartado de dades formatives se realizará conjuntamente con el RFM08
