### ISSUE TITLE
AC05:Funcionament cerca i ordenació

### ISSUE THREAD

**Issue by AmaiaMCastanos** [fev/cudu#63]
Buscador: actualment discrimina entre majúscules / minúscules i accent o no accent, no ha de discriminar aquesta búsqueda que considera a i à el mateix a efectes de cerca.
Aquesta funcionalitat també ha de ser implantada en els filtres i en la ordenació.

**Comment by llunaCreixent** [comment]
Esta issue no está acabada, verdad?
Falta la part d'accents. Potser millor crear altra issue?
